import { formatIndianCurrency } from "./csvExport";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface ExportData {
  date: string | Date;
  category?: string;
  subCategory?: string;
  merchant?: string;
  amount: number;
  description?: string;
  source?: string;
}

// Export to PDF with improved formatting
export const exportToPDF = (data: ExportData[], filename: string, title: string) => {
  const doc = new jsPDF();
  
  // Add title with better styling
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text(title, 14, 22);
  
  // Add generation date
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  doc.text(`Generated on: ${new Date().toLocaleDateString('en-IN')}`, 14, 32);
  doc.setTextColor(0);
  
  // Add a line separator
  doc.setDrawColor(200);
  doc.line(14, 36, 196, 36);
  
  // Prepare table data
  const headers = Object.keys(data[0] || {}).map(key => 
    key.charAt(0).toUpperCase() + key.slice(1).replace(/([A-Z])/g, ' $1')
  );
  
  const rows = data.map(item => 
    Object.values(item).map(val => {
      if (typeof val === 'number') return formatIndianCurrency(val);
      if (val instanceof Date) return val.toLocaleDateString('en-IN');
      return String(val);
    })
  );
  
  // Add table with improved styling
  autoTable(doc, {
    head: [headers],
    body: rows,
    startY: 42,
    styles: { 
      fontSize: 10,
      cellPadding: 4,
      lineColor: [200, 200, 200],
      lineWidth: 0.1,
    },
    headStyles: { 
      fillColor: [33, 150, 243],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      halign: 'left',
    },
    alternateRowStyles: {
      fillColor: [245, 245, 245],
    },
    margin: { left: 14, right: 14 },
  });
  
  // Calculate total if amount exists
  if (data.length > 0 && 'amount' in data[0]) {
    const total = data.reduce((sum, item) => sum + (item.amount || 0), 0);
    const finalY = (doc as any).lastAutoTable.finalY || 42;
    
    // Add total with box
    doc.setFillColor(245, 245, 245);
    doc.rect(14, finalY + 8, 182, 12, 'F');
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(`Total Amount: ${formatIndianCurrency(total)}`, 18, finalY + 16);
  }
  
  // Add footer
  const pageCount = doc.getNumberOfPages();
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text(
    `Page ${pageCount} | Generated by FinGuide`,
    doc.internal.pageSize.width / 2,
    doc.internal.pageSize.height - 10,
    { align: 'center' }
  );
  
  doc.save(filename);
};

// Export to DOCX with improved formatting
export const exportToDOCX = (data: ExportData[], filename: string, title: string) => {
  let html = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="UTF-8">
        <style>
          body { 
            font-family: 'Calibri', Arial, sans-serif; 
            margin: 40px; 
            line-height: 1.6;
          }
          h1 { 
            color: #2196F3; 
            border-bottom: 3px solid #2196F3;
            padding-bottom: 10px;
            margin-bottom: 20px;
          }
          .meta {
            color: #666;
            font-size: 12px;
            margin-bottom: 30px;
          }
          table { 
            width: 100%; 
            border-collapse: collapse; 
            margin-top: 20px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
          }
          th, td { 
            border: 1px solid #ddd; 
            padding: 12px; 
            text-align: left; 
          }
          th { 
            background-color: #2196F3; 
            color: white;
            font-weight: bold;
            text-transform: uppercase;
            font-size: 11px;
          }
          tr:nth-child(even) {
            background-color: #f9f9f9;
          }
          tr:hover {
            background-color: #f5f5f5;
          }
          .total { 
            margin-top: 30px; 
            padding: 15px;
            background-color: #f5f5f5;
            border-left: 4px solid #2196F3;
            font-weight: bold; 
            font-size: 16px; 
          }
          .footer {
            margin-top: 40px;
            text-align: center;
            color: #999;
            font-size: 10px;
            border-top: 1px solid #ddd;
            padding-top: 10px;
          }
        </style>
      </head>
      <body>
        <h1>${title}</h1>
        <p class="meta">Generated on: ${new Date().toLocaleDateString('en-IN')} at ${new Date().toLocaleTimeString('en-IN')}</p>
        <table>
          <thead>
            <tr>
  `;
  
  // Add headers
  const headers = Object.keys(data[0] || {});
  headers.forEach(key => {
    const header = key.charAt(0).toUpperCase() + key.slice(1).replace(/([A-Z])/g, ' $1');
    html += `<th>${header}</th>`;
  });
  html += '</tr></thead><tbody>';
  
  // Add rows
  data.forEach(item => {
    html += '<tr>';
    Object.values(item).forEach(val => {
      let displayVal = '';
      if (typeof val === 'number') displayVal = formatIndianCurrency(val);
      else if (val instanceof Date) displayVal = val.toLocaleDateString();
      else displayVal = String(val);
      html += `<td>${displayVal}</td>`;
    });
    html += '</tr>';
  });
  
  html += '</tbody></table>';
  
  // Add total if amount exists
  if (data.length > 0 && 'amount' in data[0]) {
    const total = data.reduce((sum, item) => sum + (item.amount || 0), 0);
    html += `<div class="total">Total Amount: ${formatIndianCurrency(total)}</div>`;
  }
  
  html += `
    <div class="footer">
      <p>Generated by FinGuide - Your Path to Financial Flourish</p>
    </div>
  </body></html>`;
  
  // Create and download
  const blob = new Blob([html], { type: 'application/msword' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
};
