import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface ExportNote {
  title: string;
  content: string;
  category: string | null;
  created_at: string;
  updated_at: string;
}

// HTML escape function to prevent XSS in exports
const escapeHtml = (unsafe: string): string => {
  return unsafe
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
};

// Export notes to PDF
export const exportNotesToPDF = (notes: ExportNote[], filename: string) => {
  const doc = new jsPDF();
  
  // Add title
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("FinNote Export", 14, 22);
  
  // Add generation date
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  doc.text(`Generated on: ${new Date().toLocaleDateString('en-IN')}`, 14, 32);
  doc.setTextColor(0);
  
  // Add a line separator
  doc.setDrawColor(200);
  doc.line(14, 36, 196, 36);
  
  let yPosition = 45;
  
  notes.forEach((note, index) => {
    // Check if we need a new page
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }
    
    // Note title
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(33, 150, 243);
    doc.text(`${index + 1}. ${note.title}`, 14, yPosition);
    yPosition += 8;
    
    // Category
    if (note.category) {
      doc.setFontSize(9);
      doc.setFont("helvetica", "italic");
      doc.setTextColor(100);
      doc.text(`Category: ${note.category}`, 14, yPosition);
      yPosition += 6;
    }
    
    // Content
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(0);
    
    const contentLines = doc.splitTextToSize(note.content, 180);
    doc.text(contentLines, 14, yPosition);
    yPosition += contentLines.length * 5 + 8;
    
    // Separator
    doc.setDrawColor(220);
    doc.line(14, yPosition, 196, yPosition);
    yPosition += 10;
  });
  
  // Add footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Page ${i} of ${pageCount} | Generated by FinGuide`,
      doc.internal.pageSize.width / 2,
      doc.internal.pageSize.height - 10,
      { align: 'center' }
    );
  }
  
  doc.save(filename);
};

// Export notes to CSV
export const exportNotesToCSV = (notes: ExportNote[], filename: string) => {
  const headers = ["Title", "Category", "Content", "Created", "Updated"];
  const rows = notes.map(note => [
    note.title,
    note.category || "Uncategorized",
    note.content.replace(/"/g, '""'), // Escape quotes
    new Date(note.created_at).toLocaleDateString('en-IN'),
    new Date(note.updated_at).toLocaleDateString('en-IN'),
  ]);
  
  const csvContent = [
    headers.join(","),
    ...rows.map(row => 
      row.map(cell => `"${cell}"`).join(",")
    ),
  ].join("\n");
  
  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const link = document.createElement("a");
  const url = URL.createObjectURL(blob);
  link.setAttribute("href", url);
  link.setAttribute("download", filename);
  link.click();
  URL.revokeObjectURL(url);
};

// Export notes to DOCX (HTML format)
export const exportNotesToDOCX = (notes: ExportNote[], filename: string) => {
  let html = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="UTF-8">
        <style>
          body { 
            font-family: 'Calibri', Arial, sans-serif; 
            margin: 40px; 
            line-height: 1.6;
          }
          h1 { 
            color: #2196F3; 
            border-bottom: 3px solid #2196F3;
            padding-bottom: 10px;
            margin-bottom: 20px;
          }
          .meta {
            color: #666;
            font-size: 12px;
            margin-bottom: 30px;
          }
          .note {
            margin-bottom: 30px;
            padding: 20px;
            border: 1px solid #ddd;
            border-radius: 8px;
            page-break-inside: avoid;
          }
          .note-title {
            color: #2196F3;
            font-size: 18px;
            font-weight: bold;
            margin-bottom: 10px;
          }
          .note-category {
            color: #666;
            font-size: 12px;
            font-style: italic;
            margin-bottom: 10px;
          }
          .note-content {
            color: #333;
            margin-bottom: 10px;
            white-space: pre-wrap;
          }
          .note-dates {
            color: #999;
            font-size: 11px;
          }
          .footer {
            margin-top: 40px;
            text-align: center;
            color: #999;
            font-size: 10px;
            border-top: 1px solid #ddd;
            padding-top: 10px;
          }
        </style>
      </head>
      <body>
        <h1>FinNote Export</h1>
        <p class="meta">Generated on: ${new Date().toLocaleDateString('en-IN')} at ${new Date().toLocaleTimeString('en-IN')}</p>
  `;
  
  notes.forEach((note, index) => {
    html += `
      <div class="note">
        <div class="note-title">${index + 1}. ${escapeHtml(note.title)}</div>
        ${note.category ? `<div class="note-category">Category: ${escapeHtml(note.category)}</div>` : ''}
        <div class="note-content">${escapeHtml(note.content)}</div>
        <div class="note-dates">
          Created: ${new Date(note.created_at).toLocaleDateString('en-IN')} | 
          Updated: ${new Date(note.updated_at).toLocaleDateString('en-IN')}
        </div>
      </div>
    `;
  });
  
  html += `
    <div class="footer">
      <p>Generated by FinGuide - Your Path to Financial Flourish</p>
    </div>
  </body></html>`;
  
  const blob = new Blob([html], { type: 'application/msword' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
};
